### ISSUE TITLE
Whisparr not able to execute both SCAN and IDENTIFY triggers for Stash Connection

### ISSUE THREAD

**Issue by PrivatePasta** [Whisparr/Whisparr#108]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Stash Connection does not trigger both `Scan: Generate Previews` and `Run Identify Task` on Import when both are enabled in the connection settings. `Scan: Generate Previews` works on it's own if IDENTIFY is disabled

### Expected Behavior

When both triggers are enabled, both should successfully trigger on import

### Steps To Reproduce

1. Add Stash Connection with the `Scan: Generate Previews` and `Run Identify Task` triggers enabled
2. Import any scene

### Environment

```markdown
- OS: Ubuntu 20.04
- Whisparr: 2.0.0.250
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/12448353/whisparr.trace.txt)

### Anything else?

I notices these 2 events in System/Events, maybe it's relevant :
![image](https://github.com/Whisparr/Whisparr/assets/63346955/653ab4e3-3094-4204-ae5d-ab5387972336)

Text version :

HttpClient :
```
HTTP Error - Res: [POST] http://stash:9999/graphql: 422.UnprocessableEntity (675 bytes)
{"errors":[{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":24,"column":64}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":25,"column":68}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":26,"column":62}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
```
NotificationService :
```
Message

Unable to send OnDownload notification to: STASH: HTTP request failed: [422:UnprocessableEntity] [POST] at [http://stash:9999/graphql]

Exception

NzbDrone.Common.Http.HttpException: HTTP request failed: [422:UnprocessableEntity] [POST] at [http://stash:9999/graphql]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 108
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 318
   at NzbDrone.Core.Notifications.Stash.StashProxy.ProcessRequest(HttpRequest request, StashSettings settings) in ./Whisparr.Core/Notifications/Stash/StashProxy.cs:line 84
   at NzbDrone.Core.Notifications.Stash.StashProxy.Update(StashSettings settings, String path) in ./Whisparr.Core/Notifications/Stash/StashProxy.cs:line 64
   at NzbDrone.Core.Notifications.Stash.StashService.Update(StashSettings settings, Series series) in ./Whisparr.Core/Notifications/Stash/StashService.cs:line 42
   at NzbDrone.Core.Notifications.Stash.Stash.OnDownload(DownloadMessage message) in ./Whisparr.Core/Notifications/Stash/Stash.cs:line 23
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeImportedEvent message) in ./Whisparr.Core/Notifications/NotificationService.cs:line 156
{"errors":[{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":24,"column":64}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":25,"column":68}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Enum \"IdentifyFieldStrategy!\" cannot represent non-enum value: \"MERGE\". Did you mean the enum value \"MERGE\"?","locations":[{"line":26,"column":62}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
```

Also, in the Discord I was directed to add the TPDB stash-box endpoint, even after adding it (pictured below) nothing has changed
![image](https://github.com/Whisparr/Whisparr/assets/63346955/052b0fc7-3ac7-4e1c-a79e-77ac260907b6)

**Comment by Qstick** [comment]
https://github.com/Whisparr/Whisparr/commit/a047c4113e39dc291a4b7d7382ac6f1572f9e959
