### ISSUE TITLE
Cannot add a site

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [Whisparr/Whisparr#123]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I try to add Penthouse, it doesn't go through.
I've tried it via Librbry Import it as well, and still same error

### Expected Behavior

Site gets added

### Steps To Reproduce

Install Whisparr on docker.
Add Penthouse.

### Environment

```markdown
- OS: OpenMediaVault
- Whisparr: 2.0.0.250
- Docker Install: nightly-f041722 by hotio
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Main

### Trace Logs?

2023-10-16 18:27:56.7|Info|AddSeriesService|Adding Series [1001][Penthouse] Path: [/adult/Penthouse]
2023-10-16 18:29:14.1|Info|ImportListSyncService|Starting Import List Sync
2023-10-16 18:29:14.1|Info|ImportListSyncService|Processing 0 list items
2023-10-16 18:29:14.1|Info|ImportListSyncService|Import List Sync Completed. Items found: 0, Series added: 0
2023-10-16 18:29:36.7|Fatal|WhisparrErrorPipeline|Request Failed. POST /api/v3/series/import

[v2.0.0.250] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection aborted.
 ---> System.Net.Sockets.SocketException (103): Connection aborted
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Whisparr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Whisparr.Common/Http/HttpClient.cs:line 141
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 298
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 304
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetSeriesInfo(Int32 tvdbSeriesId) in ./Whisparr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 47
   at NzbDrone.Core.Tv.AddSeriesService.AddSkyhookData(Series newSeries) in ./Whisparr.Core/Tv/AddSeriesService.cs:line 120
   at NzbDrone.Core.Tv.AddSeriesService.AddSeries(List`1 newSeries, Boolean ignoreErrors) in ./Whisparr.Core/Tv/AddSeriesService.cs:line 76
   at lambda_method154(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Whisparr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Whisparr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Whisparr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Whisparr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/StartingUpMiddleware.cs:line 39
   at Whisparr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Whisparr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by puckhead-nyr** [comment]
I am having same issue. Does anyone have any updates?
