### ISSUE TITLE
"Discover" option is not working

### ISSUE THREAD

**Issue by UberMetroid** [Whisparr/Whisparr#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on "Discover" Whisparr only shows "Unable to load movies"

### Expected Behavior

I expect to see a list of movies that I might like based on the movies that I are already part of my collection.

### Environment

```markdown
- OS: Docker
- Whisparr: Nightly / 0.1.0.35
- Docker Install: nightly-eb397c8 by hotio
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

![Screenshot 2022-05-14 055129](https://user-images.githubusercontent.com/4661200/168426673-f9d280d5-6eed-43d5-b04b-60ca2bd151cb.png)

**Comment by BoomHedgehog** [comment]
I can second this issue. Seems to be an issue with the parser:
```
[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 


[v0.1.0.35] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0. (Json snippet '<--error-->Permanent Redirect')

 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0.

   at Newtonsoft.Json.JsonTextReader.ParseValue()
```

**Comment by BoomHedgehog** [comment]
Further info!
Disabling the "Include Whisparr recommended movies in discovery view" allows the Discovery View to show movies from your lists. This might narrow down where the issue is, as I expect it might be in a null response of some kind from the Whisparr recommended.

![image](https://user-images.githubusercontent.com/99755574/169020836-7dd5f040-e305-4bd4-ac51-97ad05dbd9b5.png)

**Comment by austinwbest** [comment]
I cant reproduce this on .41. With or without the checkbox enabled it loads.

Please provide trace logs on .41

**Comment by BoomHedgehog** [comment]
@austinwbest 
```
2022-05-19 20:28:29.3|Trace|CommandQueueManager|Updating command status
2022-05-19 20:28:29.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-05-19 20:28:29.4|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-05-19 20:28:29.4|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-05-19 20:28:29.4|Trace|Http|Req: 122 [GET] /api/v3/command (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:29.4|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.1182007]
2022-05-19 20:28:29.5|Trace|CommandQueueManager|Getting all commands
2022-05-19 20:28:29.5|Trace|Http|Res: 122 [GET] /api/v3/command: 200.OK (28 ms)
2022-05-19 20:28:29.5|Debug|Api|[GET] /api/v3/command: 200.OK (28 ms)
2022-05-19 20:28:29.5|Trace|Http|Req: 123 [GET] /api/v3/log/file (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:29.5|Trace|Http|Res: 123 [GET] /api/v3/log/file: 200.OK (35 ms)
2022-05-19 20:28:29.5|Debug|Api|[GET] /api/v3/log/file: 200.OK (35 ms)
2022-05-19 20:28:30.7|Trace|Http|Req: 124 [GET] /api/v3/queue/details (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:30.7|Trace|Http|Req: 125 [GET] /api/v3/rootFolder (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:30.8|Trace|Http|Res: 124 [GET] /api/v3/queue/details: 200.OK (47 ms)
2022-05-19 20:28:30.8|Debug|Api|[GET] /api/v3/queue/details: 200.OK (47 ms)
2022-05-19 20:28:30.9|Debug|RootFolderService|Generating list of unmapped folders
2022-05-19 20:28:30.9|Debug|RootFolderService|0 unmapped folders detected.
2022-05-19 20:28:30.9|Trace|Http|Res: 125 [GET] /api/v3/rootFolder: 200.OK (182 ms)
2022-05-19 20:28:30.9|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (182 ms)
2022-05-19 20:28:33.5|Trace|Http|Req: 126 [GET] /api/v3/rootFolder (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:33.5|Trace|Http|Req: 127 [GET] /api/v3/importlist/movie?includeRecommendations=true (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:33.5|Trace|Http|Req: 128 [GET] /api/v3/exclusions (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:33.5|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-05-19 20:28:33.5|Trace|Http|Res: 128 [GET] /api/v3/exclusions: 200.OK (35 ms)
2022-05-19 20:28:33.5|Debug|RootFolderService|Generating list of unmapped folders
2022-05-19 20:28:33.5|Debug|Api|[GET] /api/v3/exclusions: 200.OK (35 ms)
2022-05-19 20:28:33.5|Trace|HttpClient|Req: [POST] http://api.whisparr.com/v1/movie/bulk
2022-05-19 20:28:33.5|Debug|RootFolderService|0 unmapped folders detected.
2022-05-19 20:28:33.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-05-19 20:28:33.6|Trace|Http|Res: 126 [GET] /api/v3/rootFolder: 200.OK (99 ms)
2022-05-19 20:28:33.6|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (99 ms)
2022-05-19 20:28:34.1|Trace|HttpClient|Res: [POST] http://api.whisparr.com/v1/movie/bulk: 308.PermanentRedirect (18 bytes) (578 ms)
2022-05-19 20:28:34.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.41] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0. (Json snippet '<--error-->Permanent Redirect')
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 48
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 48
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 310
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetBulkMovieInfo(List`1 tmdbIds) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 117
   at Whisparr.Api.V3.ImportLists.ImportListMoviesController.GetDiscoverMovies(Boolean includeRecommendations) in D:\a\1\s\src\Whisparr.Api.V3\ImportLists\ImportListMoviesController.cs:line 63
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Whisparr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Whisparr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Whisparr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Whisparr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Whisparr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-05-19 20:28:34.5|Trace|WhisparrErrorPipeline|Handling Exception
2022-05-19 20:28:34.5|Fatal|WhisparrErrorPipeline|Request Failed. GET /api/v3/importlist/movie

[v0.1.0.41] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0. (Json snippet '<--error-->Permanent Redirect')
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: P. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 48
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in D:\a\1\s\src\NzbDrone.Common\Serializer\Newtonsoft.Json\Json.cs:line 48
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in D:\a\1\s\src\NzbDrone.Common\Http\HttpResponse.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 310
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetBulkMovieInfo(List`1 tmdbIds) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 117
   at Whisparr.Api.V3.ImportLists.ImportListMoviesController.GetDiscoverMovies(Boolean includeRecommendations) in D:\a\1\s\src\Whisparr.Api.V3\ImportLists\ImportListMoviesController.cs:line 63
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Whisparr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Whisparr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Whisparr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Whisparr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Whisparr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Whisparr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-05-19 20:28:34.7|Trace|Http|Res: 127 [GET] /api/v3/importlist/movie?includeRecommendations=true: 500.InternalServerError (1249 ms)
2022-05-19 20:28:34.7|Debug|Api|[GET] /api/v3/importlist/movie?includeRecommendations=true: 500.InternalServerError (1249 ms)
2022-05-19 20:28:37.4|Trace|Http|Req: 129 [GET] /api/v3/health (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:37.4|Trace|Http|Req: 130 [GET] /api/v3/diskspace (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:37.4|Trace|Http|Req: 131 [GET] /api/v3/system/status (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:37.4|Trace|Http|Res: 129 [GET] /api/v3/health: 200.OK (15 ms)
2022-05-19 20:28:37.4|Trace|Http|Res: 131 [GET] /api/v3/system/status: 200.OK (39 ms)
2022-05-19 20:28:37.4|Debug|Api|[GET] /api/v3/health: 200.OK (15 ms)
2022-05-19 20:28:37.4|Debug|Api|[GET] /api/v3/system/status: 200.OK (39 ms)
2022-05-19 20:28:37.5|Trace|Http|Res: 130 [GET] /api/v3/diskspace: 200.OK (91 ms)
2022-05-19 20:28:37.5|Debug|Api|[GET] /api/v3/diskspace: 200.OK (91 ms)
2022-05-19 20:28:39.7|Trace|Http|Req: 132 [GET] /api/v3/log/file (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
2022-05-19 20:28:39.7|Trace|Http|Res: 132 [GET] /api/v3/log/file: 200.OK (27 ms)
2022-05-19 20:28:39.7|Debug|Api|[GET] /api/v3/log/file: 200.OK (27 ms)
2022-05-19 20:28:42.7|Trace|Http|Req: 133 [GET] /logfile/whisparr.trace.txt (from 172.17.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36)
```

**Comment by BoomHedgehog** [comment]
Occurs when attempting to access the discover page (under movies) if the "Whisper recommended" is checked.

**Comment by austinwbest** [comment]
I believe yours is throwing because of ```2022-05-19 20:28:34.1|Trace|HttpClient|Res: [POST] http://api.whisparr.com/v1/movie/bulk: 308.PermanentRedirect (18 bytes) (578 ms)```

**Comment by BoomHedgehog** [comment]
Indeed. So it's either an issue with the api being called, or the handling of it coming back.
