### ISSUE TITLE
Stash GraphQL Connect broken with latest Stash version

### ISSUE THREAD

**Issue by glottisfaun0000** [Whisparr/Whisparr#138]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

2023-12-28 06:39:06.8|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://stash:9999/graphql: 422.UnprocessableEntity (373 bytes)
{"errors":[{"message":"Field \"useFileMetadata\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":4,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"stripFileExtension\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":5,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
2023-12-28 06:39:06.8|Warn|NotificationService|Unable to send OnDownload notification to: Stash

### Expected Behavior

Stash updated recently and it seems something changed about its graphql implementation. I had some curl webhooks set up  for something else that I had to alter but I didn't pay close attention to how I changed it / don't have a backup of the previous version :-( sorry I can't be of more help, I'm not experienced with graphql either. But here's the StashApp API docs which are up to date (the examples work) https://docs.stashapp.cc/networking/api/

Also, the Test in Connect settings will "succeed".

In the meantime I created a custom script with equivalent curl commands but get this error:
```
An error occurred trying to start process '/config/custom-stash.sh' with working directory '/run/s6-rc:s6-rc-init:aNLahL/servicedirs/service-whisparr'. Exec format error
```
any idea why that would happen?

### Steps To Reproduce

1. Be on Stash v0.24.0 and trigger a scan from Whisparr

### Environment

```markdown
- OS: Debian 12
- Whisparr: 2.0.0.313
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser:
- Database: Sqlite 3.41.2
```

### What branch are you running?

Main

### Trace Logs?

2023-12-28 07:10:25.4|Trace|HttpClient|Req: [POST] http://stash:9999/graphql
2023-12-28 07:10:25.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-12-28 07:10:25.4|Trace|HttpClient|Res: HTTP/1.1 [POST] http://stash:9999/graphql: 422.UnprocessableEntity (373 bytes)
{"errors":[{"message":"Field \"useFileMetadata\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":4,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"stripFileExtension\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":5,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null} (4 ms)
2023-12-28 07:10:25.4|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [POST] http://stash:9999/graphql: 422.UnprocessableEntity (373 bytes)
{"errors":[{"message":"Field \"useFileMetadata\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":4,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"stripFileExtension\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":5,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
2023-12-28 07:10:25.4|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<INotification>
2023-12-28 07:10:25.4|Warn|NotificationService|Unable to send OnDownload notification to: Stash

[v2.0.0.313] NzbDrone.Common.Http.HttpException: HTTP request failed: [422:UnprocessableEntity] [POST] at [http://stash:9999/graphql]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in ./Whisparr.Common/Http/HttpClient.cs:line 363
   at NzbDrone.Core.Notifications.Stash.StashProxy.ProcessRequest(HttpRequest request, StashSettings settings) in ./Whisparr.Core/Notifications/Stash/StashProxy.cs:line 88
   at NzbDrone.Core.Notifications.Stash.StashProxy.Update(StashSettings settings, String path) in ./Whisparr.Core/Notifications/Stash/StashProxy.cs:line 65
   at NzbDrone.Core.Notifications.Stash.StashService.Update(StashSettings settings, Series series) in ./Whisparr.Core/Notifications/Stash/StashService.cs:line 42
   at NzbDrone.Core.Notifications.Stash.Stash.OnDownload(DownloadMessage message) in ./Whisparr.Core/Notifications/Stash/Stash.cs:line 23
   at NzbDrone.Core.Notifications.NotificationService.Handle(EpisodeImportedEvent message) in ./Whisparr.Core/Notifications/NotificationService.cs:line 160
{"errors":[{"message":"Field \"useFileMetadata\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":4,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}},{"message":"Field \"stripFileExtension\" is not defined by type \"ScanMetadataInput\".","locations":[{"line":5,"column":34}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}

**Comment by leadwolfx** [comment]
Same error with same versions on both

**Comment by glottisfaun0000** [comment]
Yep, can confirm update has my instance working. Thanks folks happy new year.
