### ISSUE TITLE
Add A Performer and Monitor their Scenes regardless of Studio

### ISSUE THREAD

**Issue by maroonedbaboon** [Whisparr/Whisparr#214]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The way I work is that I see a performer I like, I want to follow them - download their latest and upcoming scenes.
I don't mind which studio they're working with (as long as it's not truly grim!).

I don't wish to have the entirety of a studio on my server.
Adding every studio to then use the Performer page somewhat effectively feels backwards?

I hope it's not just me that thinks this way? :D

So to put that into context:
In V3, currently there's not a way to add a performer, and then monitor that performer's scenes regardless of studio.
You need to add scenes, then those scenes populate the performer page which acts as a filter. 

It'd be great if the Performer page were a starting point.

### Describe the solution you'd like

Can we please have a way to...

1. Add a Performer by searching for them. "Madison Wilde" -> Oh look there she is -> added to performer list.
2. Monitor that Performer's scenes, past and future, regardless of studio / movie / scenes already added to Whisparr separately.

Thinking of the current Performer page, it'd be a chart of their work with the most recent on top, presumably laid out as rows of :

Monitor Button | Studio | Title | Release Date | Search & Grab Buttons

So, an amendment to the current layout that separates rows out by Studio.

### Describe alternatives you've considered

At the mo, I've got a sabnzbd rss feed going, filtered by the performers I like, pointed at an indexer. It's pretty good! But definitely unrefined.

### Anything else?

Thank you!

**Comment by plz12345** [comment]
> ### Is there an existing issue for this?
> 
> 
> 
> - [X] I have searched the existing open and closed issues
> 
> 
> 
> ### Is your feature request related to a problem? Please describe
> 
> 
> 
> The way I work is that I see a performer I like, I want to follow them - download their latest and upcoming scenes.
> 
> I don't mind which studio they're working with (as long as it's not truly grim!).
> 
> 
> 
> I don't wish to have the entirety of a studio on my server.
> 
> Adding every studio to then use the Performer page somewhat effectively feels backwards?
> 
> 
> 
> I hope it's not just me that thinks this way? :D
> 
> 
> 
> So to put that into context:
> 
> In V3, currently there's not a way to add a performer, and then monitor that performer's scenes regardless of studio.
> 
> You need to add scenes, then those scenes populate the performer page which acts as a filter. 
> 
> 
> 
> It'd be great if the Performer page were a starting point.
> 
> 
> 
> ### Describe the solution you'd like
> 
> 
> 
> Can we please have a way to...
> 
> 
> 
> 1. Add a Performer by searching for them. "Madison Wilde" -> Oh look there she is -> added to performer list.
> 
> 2. Monitor that Performer's scenes, past and future, regardless of studio / movie / scenes already added to Whisparr separately.
> 
> 
> 
> Thinking of the current Performer page, it'd be a chart of their work with the most recent on top, presumably laid out as rows of :
> 
> 
> 
> Monitor Button | Studio | Title | Release Date | Search & Grab Buttons
> 
> 
> 
> So, an amendment to the current layout that separates rows out by Studio.
> 
> 
> 
> ### Describe alternatives you've considered
> 
> 
> 
> At the mo, I've got a sabnzbd rss feed going, filtered by the performers I like, pointed at an indexer. It's pretty good! But definitely unrefined.
> 
> 
> 
> ### Anything else?
> 
> 
> 
> Thank you!

All you need to do is add one scene, then monitor the performer.

**Comment by maroonedbaboon** [comment]
@plz12345 Thanks for the heads-up! 

It's a little unintuitive but yeah, after adding a scene, then monitoring the performer, then whacking refresh on the performer, the performer page does indeed populate. Neat!

However the main requests from the ticket still stand:

1. Please add the ability to add a performer directly from the performer page.
2. When adding a performer, please give the ability to select whether to monitor all / upcoming / previous scenes.

**Comment by plz12345** [comment]
> @plz12345 Thanks for the heads-up! 
> 
> 
> 
> It's a little unintuitive but yeah, after adding a scene, then monitoring the performer, then whacking refresh on the performer, the performer page does indeed populate. Neat!
> 
> 
> 
> However the main requests from the ticket still stand:
> 
> 
> 
> 1. Please add the ability to add a performer directly from the performer page.
> 
> 2. When adding a performer, please give the ability to select whether to monitor all / upcoming / previous scenes.
> 
> 

1 is feasible, 2 is basically "use v2 instead".  It's native to the Sonarr base code, not Radarr's.

**Comment by maroonedbaboon** [comment]
OK, but when I monitor a performer and refresh, that adds all of their scenes into Whisparr... and automatically starts trying to download every single one immediately.

Then there's no quick way of selecting all scenes for a performer and selecting "stop monitoring these".
So you're stuck with Whisparr desperately trying to "complete" the performer and no way to stop it from trying to fulfil that task without unmonitoring every scene individually.

A performer is a show, the studios are seasons and the scenes are episodes... So not having the ability to address the studios and scenes for a performer en mass is pretty unweildy right?

I understand this release is intended to be based around performers so it'd be great to make the approach easier.

EDIT - or, in Radarr terminology, you'd have the Performer page, their Collections (Studios) then Films within those Collections (scenes).

**Comment by plz12345** [comment]
> OK, but when I monitor a performer and refresh, that adds all of their scenes into Whisparr... and automatically starts trying to download every single one immediately.
> 
> Then there's no quick way of selecting all scenes for a performer and selecting "stop monitoring these". So you're stuck with Whisparr desperately trying to "complete" the performer and no way to stop it from trying to fulfil that task without unmonitoring every scene individually.
> 
> A performer is a show, the studios are seasons and the scenes are episodes... So not having the ability to address the studios and scenes for a performer en mass is pretty unweildy right?
> 
> I understand this release is intended to be based around performers so it'd be great to make the approach easier.
> 
> EDIT - or, in Radarr terminology, you'd have the Performer page, their Collections (Studios) then Films within those Collections (scenes).

You have the "Search on Add" setting enabled prior to that.  Disable it, and you can un-monitor the scenes you don't want it to fetch.

**Comment by maroonedbaboon** [comment]
Gotcha! Thanks again. 

OK, I've found a performer via the scenes menu, unticked search on add, and added them, then refreshed the scenes in the performer page. The Performer's page is showing...

1. Performer - Monitored
2. Studios - Unmonitored
3. Existing Scenes - Monitored and marked missing.

It doesn't really add up to expectations, or add up in the UI yet:

**1 Performer**
This is good - I want to monitor the performer, Whisparr monitors the performer.
As we agreed, moving the Performer "search and add" from the Scenes menu into the Performer menu would make the UI clearer.

**2 Studio**
I can't click to monitor studios in the Performer page.
At the moment if a performer releases a new scene under one of those existing studios, it looks like it wont be monitored.
Presumably that's not the case - it'll download regardless.

So these greyed out studio monitor buttons are actually preventing all of the scenes flagged as monitored and missing from downloading. That's awkward.

If Whisparr had the ability to monitor "scenes for this performer AND from this studio" or "this performer NOT these studios" that would be great and make those monitor buttons useful.

**3 Existing Scenes**
All of the performer's existing scenes are flagging up as monitored and missing.
I'm only interested in upcoming scenes, so thats unexpected.
I can see that I can unmonitor them en mass in the scene tab so can correct things.

I reckon it'd still be useful to be able to say "monitor upcoming" when adding a studio or scene.

Thanks once again!

**Comment by plz12345** [comment]
Everything you've written so far just screams "I should be using v2".

1. Correct
2. Incorrect, a studio doesn't need to be monitored for the scene to be monitored.  Removing the toggle for monitoring Studio from the Performer view is intentional, to avoid the confusion there.  In v2, studio is the top level because that's how Sonarr works.  In v3 that is not he case.
3. As previously noted, this is on purpose, and if you want "only future scenes" as an out of the box solution, just use v2.  Just note that both versions, when desiring to monitor a performer, assume you want everything by them, not just future releases.

**Comment by rlab88** [comment]
> @plz12345 Thanks for the heads-up!
> 
> It's a little unintuitive but yeah, after adding a scene, then monitoring the performer, then whacking refresh on the performer, **the performer page does indeed populate**. Neat!
> 
> However the main requests from the ticket still stand:
> 
>     1. Please add the ability to add a performer directly from the performer page.
> 
>     2. When adding a performer, please give the ability to select whether to monitor all / upcoming / previous scenes.

Question: how to do you see the performer page? I've tried doing this, and I don't see any way to get to a page that shows the performers scenes, it just adds a ton of studios en masse with that performer's scene monitored. I'm using version 2.0.0.548 if that helps.

**Comment by BRFreshness** [comment]
I was curious to try adding a performer. I pulled up a scene that was downloaded, clicked the flag to monitor that performer and (maybe foolishly?) didn't unselect the "Search on Add" checkbox. I clicked the "Test" button at the bottom and got a green check-mark, so I clicked "OK". Nothing happened for a few seconds and then I saw that it started searching all studios for that performer. It found about 50 or 60 scenes... and it appears to be successfully downloading them now.

However, a few minutes later the GUI "broke" and only presents the following message: 
```
database disk image is malformed database disk image is malformed
Version 2.0.0.548
```
I see the following from the log:
```
[Error] WhisparrErrorPipeline: [GET /api/v3/series] 

[v2.0.0.548] code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1094
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at NzbDrone.Core.SeriesStats.SeriesStatisticsRepository.Query(SqlBuilder builder, String template) in ./Whisparr.Core/SeriesStats/SeriesStatisticsRepository.cs:line 65
   at NzbDrone.Core.SeriesStats.SeriesStatisticsRepository.SeriesStatistics() in ./Whisparr.Core/SeriesStats/SeriesStatisticsRepository.cs:line 32
   at NzbDrone.Core.SeriesStats.SeriesStatisticsService.SeriesStatistics() in ./Whisparr.Core/SeriesStats/SeriesStatisticsService.cs:line 23
   at Whisparr.Api.V3.Series.SeriesController.AllSeries(Nullable`1 tvdbId, Boolean includeSeasonImages) in ./Whisparr.Api.V3/Series/SeriesController.cs:line 99
   at lambda_method12(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Whisparr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Whisparr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Whisparr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Whisparr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/StartingUpMiddleware.cs:line 39
   at Whisparr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Whisparr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Whisparr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Aside from that, the program appears to still be working: it is moving downloaded scenes from the completed download folder to my media library. 

How do I fix this? I have a db file backup from yesterday, I think. Should I simply shut down then copy the backup database over the corrupt one? Or is there a way to repair the database file?

How did this happen? What might I have done wrong?

Thanks.

**Comment by xDaveN** [comment]
> Question: how to do you see the performer page? I've tried doing this, and I don't see any way to get to a page that shows the performers scenes, it just adds a ton of studios en masse with that performer's scene monitored. I'm using version 2.0.0.548 if that helps.

Been wondering as well. Is there just no way to monitor performers on 2.0.0.548?
I'm a bit confused Whisparr is based on studios/sites anyways, don't most people look up specific performers anyways, unless a studio does niche stuff?

**Comment by BRFreshness** [comment]
Circling back around to this issue to post an update. I replaced the database file with a backup from a day or so earlier. Once Whisparr was working I again tried to monitor a performer. It does work, but if you're not careful it will attempt to download everything that performer appears in. (well - duh - that's the point I guess?) 

Whisparr v3 is simply not designed for that feature. It's okay - I can live without it.

**Comment by xDaveN** [comment]
> Whisparr v3 is simply not designed for that feature. It's okay - I can live without it.

Does v2 offer performer tracking similar to how sites are tracked in v3? (:

**Comment by plz12345** [comment]
Closing this.  What you can use for this use case is a StashDB Performer Import List.  It is not one click, but it will give you the ability to add the performer and choose to either download, or just list, their scenes.  Alternatively, you can use a StashDB Favorites Import List to do this with multiple performers, which you'd favorite on StashDB itself.  You need to join, get an API key, for both of these, but it provides flexibility.
