### ISSUE TITLE
TMDb search fails with NzbDrone.Common.Http.UnexpectedHtmlContentException

### ISSUE THREAD

**Issue by wmassingham** [Whisparr/Whisparr#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to add new or match existing content via TMDb API fails with NzbDrone.Common.Http.UnexpectedHtmlContentException

### Expected Behavior

Valid results returned

### Steps To Reproduce

1. Create whisparr container
2. Add new, search for any string
3. Observe failure

### Environment

```markdown
- OS: AlmaLinux release 8.6 (Sky Tiger)
- Whisparr: 0.1.0.49
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: n/a
```

### What branch are you running?

Nightly

### Trace Logs?

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/9485228/whisparr.trace.txt)

**Comment by wmassingham** [comment]
The weird thing is that the log says it got an HTTP 308 redirect, but if I use curl from inside the container, I get a 200 and the expected API data.

I'm not sure if this is a bug in Whisparr or the API proxy, or in nzbdrone.

Edit: I think maybe the redirect is just http->https? Should whisparr just request HTTPS in the first place?

**Comment by kaibae19** [comment]
I saw this earlier as well:

```
today at 11:22:00 AM[Warn] SkyHookProxy: NzbDrone.Common.Http.UnexpectedHtmlContentException: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. **[http://api.whisparr.com/v1/search?q=hot&year=]**

today at 11:22:00 AM[v0.1.0.49] NzbDrone.Common.Http.UnexpectedHtmlContentException: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [http://api.whisparr.com/v1/search?q=hot&year=]

today at 11:22:00 AM   at NzbDrone.Common.Http.HttpClient.CheckResponseContentType(HttpResponse response) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 317

today at 11:22:00 AM   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest  #request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 289

today at 11:22:00 AM   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 436

today at 11:22:00 AM<center><h1>308 Permanent Redirect</h1></center>

today at 11:22:00 AM[Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. 

today at 11:22:00 AM[v0.1.0.49] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'hot' failed. Unable to communicate with TMDb.
```


For a search of 'hot' in the GUI, we appear to be generating a search at: http://api.whisparr.com/v1/search?q=hot&year= 

If I provide that URL to a web browser, it redirects to a https response and provides the JSON data needed by the query.  It would see that where this request is being made, it should be updated to https://api.whisparr.com as the same query on https responds with a HTTP 200.

**Comment by derpindialer** [comment]
I am also getting this exception:

```
NzbDrone.Common.Http.UnexpectedHtmlContentException: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [http://api.whisparr.com/v1/movie/1020570]
   at NzbDrone.Common.Http.HttpClient.CheckResponseContentType(HttpResponse response) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 317
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 289
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo(Int32 tmdbId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 81
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 325
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>

```
Running Nightly on Docker.

**Comment by rmangaha** [comment]
I’ve run into this to and in my experiments I believe it may be related to http://api.whisparr.com/ not being https. I was able to recreate with a curl within the container, but when https, the expected data appears.

**Comment by wmassingham** [comment]
I probably did something wrong making that pr because it was entirely in the browser (probs could have just cherry-picked the commit) but I think it should fix the issue

Not following the 308 is an upstream issue but I can't quite follow the source so I created a thread on the sonarr forums (https://forums.sonarr.tv/t/nzbdrone-appears-to-ignore-http-308-redirect/30708)

**Comment by kaibae19** [comment]
I worked around this bug by the setting up a load balancer to answer for http://api.whisparr.com and to transform the request to https.  Search function is now currently working in Whisparr app with this workaround in place.

**Comment by derpindialer** [comment]
I am receiving the following error on List Sync after updating to Nightly 0.1.0.53:

```
Error during Import List Sync for list TMDb Person: Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovie.get_TmdbId() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListMovies\ImportListMovie.cs:line 25
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_1.<SyncMoviesForList>b__4(ImportListMovie e) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListMovies\ImportListMovieService.cs:line 48
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.<>c__DisplayClass5_0.<SyncMoviesForList>b__0(ImportListMovie l) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListMovies\ImportListMovieService.cs:line 48
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at NzbDrone.Core.ImportLists.ImportListMovies.ImportListMovieService.SyncMoviesForList(List`1 listMovies, Int32 listId) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListMovies\ImportListMovieService.cs:line 46
   at NzbDrone.Core.ImportLists.FetchAndParseImportListService.<>c__DisplayClass7_2.<Fetch>b__2() in D:\a\1\s\src\NzbDrone.Core\ImportLists\FetchAndParseImportListService.cs:line 106
```

**Comment by derpindialer** [comment]
Oddly enough, I'm finally not getting errors anymore, and it's finally able to search and download from lists now. Thanks!
