### ISSUE TITLE
Initial install SQL Error

### ISSUE THREAD

**Issue by l2noob2** [Whisparr/Whisparr#66]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Upon initial install, receive the following error when first attempting to connect to web interface: **SQL logic error no such column: true**

### Expected Behavior

The web interface should load.

### Steps To Reproduce

Fresh install on ubuntu.

### Environment

```markdown
- OS: Ubuntu Linux 18.04.6 LTS
- Whisparr:nightly, today 4/10/2023
- Docker Install:no
- Using Reverse Proxy:no
- Browser:chrome
```

### What branch are you running?

Main

### Trace Logs?

2023-04-10 14:02:32.7|Info|FluentMigrator.Runner.MigrationRunner|3: remove_rarbg migrated
2023-04-10 14:02:32.7|Info|FluentMigrator.Runner.MigrationRunner|=> 0.0056516s
2023-04-10 14:02:33.6|Info|Microsoft.Hosting.Lifetime|Now listening on: http://[::]:6969
2023-04-10 14:02:34.0|Info|QualityProfileService|Setting up default quality profiles
2023-04-10 14:02:34.2|Info|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2023-04-10 14:02:34.2|Info|Microsoft.Hosting.Lifetime|Hosting environment: Production
2023-04-10 14:02:34.2|Info|Microsoft.Hosting.Lifetime|Content root path: /
2023-04-10 14:02:40.7|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v2.0.0.146] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: true
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()

**Comment by Qstick** [comment]
Please provide a full log. Thanks

**Comment by l2noob2** [comment]
[prowlarr.txt](https://github.com/Whisparr/Whisparr/files/11209867/prowlarr.txt)

**Comment by thezak48** [comment]
> [prowlarr.txt](https://github.com/Whisparr/Whisparr/files/11209867/prowlarr.txt)

This is Prowlarr logs not Whisparr, also this is info logs when we need trace logs

**Comment by l2noob2** [comment]
Apologies! It's early, that's my excuse. Since I am never able to start the application I cannot change logging to trace. It stops immediately with an error.
[whisparr (1).txt](https://github.com/Whisparr/Whisparr/files/11210132/whisparr.1.txt)

**Comment by ItsKy1e** [comment]
I have the same issue and I was able to turn on the trace debugs via the config file. I also checked the regular logs and debug logs, but they are all the same. 

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/11211675/whisparr.trace.txt)

**Comment by l2noob2** [comment]
[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/11211816/whisparr.trace.txt)
 Adding one more to the pile.

**Comment by ItsKy1e** [comment]
Hi All,

After reinstalling with 2.0.0.151, I am now getting an SQL error for column is False.

[v2.0.0.151] code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: false

[whisparr.trace.txt](https://github.com/Whisparr/Whisparr/files/11222522/whisparr.trace.txt)
