### ISSUE TITLE
Postgres Error

### ISSUE THREAD

**Issue by telix5000** [Whisparr/Whisparr#79]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am getting this strange error when doing a search for all. I can select a page at a time, but when I run a mass search this erorr occurs.

[v2.0.0.172] Npgsql.PostgresException (0x80004005): 42702: ORDER BY "Id" is ambiguous

POSITION: 366
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1470
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1451
   at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1306
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 50
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func`3 mapper) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 156
   at NzbDrone.Core.Tv.EpisodeRepository.PagedQuery(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeRepository.cs:line 48
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 434
   at NzbDrone.Core.Tv.EpisodeRepository.EpisodesWithoutFiles(PagingSpec`1 pagingSpec, Boolean includeSpecials) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeRepository.cs:line 121
   at NzbDrone.Core.Tv.EpisodeService.EpisodesWithoutFiles(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeService.cs:line 154
   at NzbDrone.Core.IndexerSearch.EpisodeSearchService.Execute(MissingEpisodeSearchCommand message) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\EpisodeSearchService.cs:line 153
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 84
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
  Exception data:
    Severity: ERROR
    SqlState: 42702
    MessageText: ORDER BY "Id" is ambiguous
    Position: 366
    File: parse_clause.c
    Line: 1964
    Routine: findTargetlistEntrySQL92

### Expected Behavior

It should just search, but it errors out.

### Environment

```markdown
- OS: Docker
- Whisparr: Newest
- Docker Install: Latest
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

[v2.0.0.172] Npgsql.PostgresException (0x80004005): 42702: ORDER BY "Id" is ambiguous

POSITION: 366
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1470
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1451
   at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1306
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 50
   at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func`3 mapper) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 156
   at NzbDrone.Core.Tv.EpisodeRepository.PagedQuery(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeRepository.cs:line 48
   at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 434
   at NzbDrone.Core.Tv.EpisodeRepository.EpisodesWithoutFiles(PagingSpec`1 pagingSpec, Boolean includeSpecials) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeRepository.cs:line 121
   at NzbDrone.Core.Tv.EpisodeService.EpisodesWithoutFiles(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Tv\EpisodeService.cs:line 154
   at NzbDrone.Core.IndexerSearch.EpisodeSearchService.Execute(MissingEpisodeSearchCommand message) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\EpisodeSearchService.cs:line 153
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 84
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
  Exception data:
    Severity: ERROR
    SqlState: 42702
    MessageText: ORDER BY "Id" is ambiguous
    Position: 366
    File: parse_clause.c
    Line: 1964
    Routine: findTargetlistEntrySQL92

**Comment by Qstick** [comment]
a353353b9125fd516eb72c7cfc19ff55069b4b4b
